### ISSUE TITLE
Mod doesn't work with Lure API (Sulayre.Lure)

### ISSUE THREAD

**Issue by RemiFoxin** [sophiethefox/VoiceTrainedSpecies-Webfishing#1]
Voices return to default when Lure is also installed.

**Comment by sophiethefox** [comment]
seems to be due to my mod overwriting all instances of the sound string here to the opposite species
https://github.com/sophiethefox/VoiceTrainedSpecies-Webfishing/blob/87b2e81e2b5aedc42e6aa434a830c582cb340bfd/VoiceTrainedSpecies/DogBarkPatch.cs#L16
while Lure is overwriting bark_id afterwards
https://github.com/Sulayre/WebfishingLure/blob/db02ebf96c6f8ce7656d7624ed07a4be2bbe4683/ModCSharp/Patches/BarkPatcher.cs#L58
i'll look into fixing this soon

**Comment by ohgeezthea** [comment]
having the same issues, im also not too educated on code or anything (i know the basics lol) so it was also difficult figuring out where specifically id need to change the voice i use

**Comment by RemiFoxin** [comment]
Also, since thunderstore is kicking off. Will this mod be moved there too?

**Comment by sophiethefox** [comment]
Fixed with [1.2](https://github.com/sophiethefox/VoiceTrainedSpecies-Webfishing/releases/tag/1.2)
Will be publishing to thunderstore in the coming days

@ohgeezthea it's changed in `GDWeave/configs/VoiceTrainedSpecies.json` (load the mod once to create the config)
